import type { MidiFrame } from "./types"

function note(name: string, midi: number, velocity = 0.8, duration = 0.25): { name: string; midi: number; velocity: number; duration: number } {
  return { name, midi, velocity, duration }
}

export const presetMelodies: Record<string, { name: string; description: string; frames: MidiFrame[] }> = {
  "twinkle-twinkle": {
    name: "Twinkle Twinkle Little Star",
    description: "A classic nursery rhyme melody",
    frames: [
      { time: 0, notes: [note("C4", 60)] },
      { time: 0.5, notes: [note("C4", 60)] },
      { time: 1, notes: [note("G4", 67)] },
      { time: 1.5, notes: [note("G4", 67)] },
      { time: 2, notes: [note("A4", 69)] },
      { time: 2.5, notes: [note("A4", 69)] },
      { time: 3, notes: [note("G4", 67)] },
      { time: 4, notes: [note("F4", 65)] },
      { time: 4.5, notes: [note("F4", 65)] },
      { time: 5, notes: [note("E4", 64)] },
      { time: 5.5, notes: [note("E4", 64)] },
      { time: 6, notes: [note("D4", 62)] },
      { time: 6.5, notes: [note("D4", 62)] },
      { time: 7, notes: [note("C4", 60)] },
      { time: 8, notes: [note("G4", 67)] },
      { time: 8.5, notes: [note("G4", 67)] },
      { time: 9, notes: [note("F4", 65)] },
      { time: 9.5, notes: [note("F4", 65)] },
      { time: 10, notes: [note("E4", 64)] },
      { time: 10.5, notes: [note("E4", 64)] },
      { time: 11, notes: [note("D4", 62)] },
      { time: 12, notes: [note("G4", 67)] },
      { time: 12.5, notes: [note("G4", 67)] },
      { time: 13, notes: [note("F4", 65)] },
      { time: 13.5, notes: [note("F4", 65)] },
      { time: 14, notes: [note("E4", 64)] },
      { time: 14.5, notes: [note("E4", 64)] },
      { time: 15, notes: [note("D4", 62)] },
    ],
  },
  "ode-to-joy": {
    name: "Ode to Joy",
    description: "Beethoven's famous melody from Symphony No. 9",
    frames: [
      { time: 0, notes: [note("E4", 64)] },
      { time: 0.5, notes: [note("E4", 64)] },
      { time: 1, notes: [note("F4", 65)] },
      { time: 1.5, notes: [note("G4", 67)] },
      { time: 2, notes: [note("G4", 67)] },
      { time: 2.5, notes: [note("F4", 65)] },
      { time: 3, notes: [note("E4", 64)] },
      { time: 3.5, notes: [note("D4", 62)] },
      { time: 4, notes: [note("C4", 60)] },
      { time: 4.5, notes: [note("C4", 60)] },
      { time: 5, notes: [note("D4", 62)] },
      { time: 5.5, notes: [note("E4", 64)] },
      { time: 6, notes: [note("E4", 64)] },
      { time: 7, notes: [note("D4", 62)] },
      { time: 7.5, notes: [note("D4", 62)] },
      { time: 8, notes: [note("E4", 64)] },
      { time: 8.5, notes: [note("E4", 64)] },
      { time: 9, notes: [note("F4", 65)] },
      { time: 9.5, notes: [note("G4", 67)] },
      { time: 10, notes: [note("G4", 67)] },
      { time: 10.5, notes: [note("F4", 65)] },
      { time: 11, notes: [note("E4", 64)] },
      { time: 11.5, notes: [note("D4", 62)] },
      { time: 12, notes: [note("C4", 60)] },
      { time: 12.5, notes: [note("C4", 60)] },
      { time: 13, notes: [note("D4", 62)] },
      { time: 13.5, notes: [note("E4", 64)] },
      { time: 14, notes: [note("D4", 62)] },
      { time: 15, notes: [note("C4", 60)] },
      { time: 15.5, notes: [note("C4", 60)] },
    ],
  },
  "canon-in-d": {
    name: "Canon in D (Pachelbel)",
    description: "The iconic Canon progression with chords",
    frames: [
      { time: 0, notes: [note("D4", 62), note("F#4", 66), note("A4", 69)] },
      { time: 1, notes: [note("A3", 57), note("C#4", 61), note("E4", 64)] },
      { time: 2, notes: [note("B3", 59), note("D4", 62), note("F#4", 66)] },
      { time: 3, notes: [note("F#3", 54), note("A3", 57), note("C#4", 61)] },
      { time: 4, notes: [note("G3", 55), note("B3", 59), note("D4", 62)] },
      { time: 5, notes: [note("D3", 50), note("F#3", 54), note("A3", 57)] },
      { time: 6, notes: [note("G3", 55), note("B3", 59), note("D4", 62)] },
      { time: 7, notes: [note("A3", 57), note("C#4", 61), note("E4", 64)] },
      { time: 8, notes: [note("D4", 62), note("F#4", 66), note("A4", 69)] },
      { time: 9, notes: [note("A3", 57), note("C#4", 61), note("E4", 64)] },
      { time: 10, notes: [note("B3", 59), note("D4", 62), note("F#4", 66)] },
      { time: 11, notes: [note("F#3", 54), note("A3", 57), note("C#4", 61)] },
      { time: 12, notes: [note("G3", 55), note("B3", 59), note("D4", 62)] },
      { time: 13, notes: [note("D3", 50), note("F#3", 54), note("A3", 57)] },
      { time: 14, notes: [note("G3", 55), note("B3", 59), note("D4", 62)] },
      { time: 15, notes: [note("A3", 57), note("C#4", 61), note("E4", 64)] },
    ],
  },
  "c-major-scale": {
    name: "C Major Scale",
    description: "Simple ascending and descending C major scale",
    frames: [
      { time: 0, notes: [note("C4", 60)] },
      { time: 0.5, notes: [note("D4", 62)] },
      { time: 1, notes: [note("E4", 64)] },
      { time: 1.5, notes: [note("F4", 65)] },
      { time: 2, notes: [note("G4", 67)] },
      { time: 2.5, notes: [note("A4", 69)] },
      { time: 3, notes: [note("B4", 71)] },
      { time: 3.5, notes: [note("C5", 72)] },
      { time: 4, notes: [note("C5", 72)] },
      { time: 4.5, notes: [note("B4", 71)] },
      { time: 5, notes: [note("A4", 69)] },
      { time: 5.5, notes: [note("G4", 67)] },
      { time: 6, notes: [note("F4", 65)] },
      { time: 6.5, notes: [note("E4", 64)] },
      { time: 7, notes: [note("D4", 62)] },
      { time: 7.5, notes: [note("C4", 60)] },
    ],
  },
  "fur-elise": {
    name: "Für Elise (Theme)",
    description: "The famous opening theme by Beethoven",
    frames: [
      { time: 0, notes: [note("E5", 76)] },
      { time: 0.25, notes: [note("D#5", 75)] },
      { time: 0.5, notes: [note("E5", 76)] },
      { time: 0.75, notes: [note("D#5", 75)] },
      { time: 1, notes: [note("E5", 76)] },
      { time: 1.25, notes: [note("B4", 71)] },
      { time: 1.5, notes: [note("D5", 74)] },
      { time: 1.75, notes: [note("C5", 72)] },
      { time: 2, notes: [note("A4", 69)] },
      { time: 3, notes: [note("C4", 60)] },
      { time: 3.25, notes: [note("E4", 64)] },
      { time: 3.5, notes: [note("A4", 69)] },
      { time: 4, notes: [note("B4", 71)] },
      { time: 5, notes: [note("E4", 64)] },
      { time: 5.25, notes: [note("G#4", 68)] },
      { time: 5.5, notes: [note("B4", 71)] },
      { time: 6, notes: [note("C5", 72)] },
      { time: 7, notes: [note("E5", 76)] },
      { time: 7.25, notes: [note("D#5", 75)] },
      { time: 7.5, notes: [note("E5", 76)] },
      { time: 7.75, notes: [note("D#5", 75)] },
      { time: 8, notes: [note("E5", 76)] },
      { time: 8.25, notes: [note("B4", 71)] },
      { time: 8.5, notes: [note("D5", 74)] },
      { time: 8.75, notes: [note("C5", 72)] },
      { time: 9, notes: [note("A4", 69)] },
    ],
  },
  "chromatic": {
    name: "Chromatic Run",
    description: "All 12 semitones ascending - tests full range",
    frames: Array.from({ length: 24 }, (_, i) => ({
      time: i * 0.25,
      notes: [note(
        ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"][i % 12] + String(Math.floor(i / 12) + 3),
        48 + i,
      )],
    })),
  },
}

export const presetList = Object.entries(presetMelodies).map(([id, data]) => ({
  id,
  name: data.name,
  description: data.description,
  frameCount: data.frames.length,
}))
